export const GET_FILM_DATA = 'GET_FILM_DATA';
export const GET_FILM_DATA_FAILED = 'GET_FILM_DATA_FAILED';

export const GET_FILM_DATA_BY_QUERY = 'GET_FILM_DATA_BY_QUERY';
export const GET_FILM_DATA_BY_QUERY_FAILED = 'GET_FILM_DATA_BY_QUERY_FAILED';

export const GET_FILM_TOP_RATED = 'GET_FILM_TOP_RATED';
export const GET_FILM_TOP_RATED_FAILED = 'GET_FILM_TOP_RATED_FAILED';

export const GET_FILM_UPCOMING = 'GET_FILM_UPCOMING';
export const GET_FILM_UPCOMING_FAILED = 'GET_FILM_UPCOMING_FAILED';

export const GET_MOVIES_POPULAR = 'GET_MOVIES_POPULAR';
export const GET_MOVIES_POPULAR_FAILED = 'GET_MOVIES_POPULAR_FAILED';

export const GET_VIDEO_DATA = 'GET_VIDEO_DATA';
export const GET_VIDEO_DATA_FAILED = 'GET_VIDEO_DATA_FAILED';
